on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Upload binaries to Releases page?'
        required: true
        type: boolean
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_dist:
    runs-on: macos-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v5
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore .NET tools and node packages - build.sh
      run: ./build.sh -t Build
    - name: Build app - build_dist.sh
      run: ./build_dist.sh
    - name: Deploy to releases page
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'push' || inputs.release }}
      with:
        files: dist/issie-[0-9]+.[0-9]+.[0-9]+-*-*.*
